app/routes.php
<?php

Route::get('/signup', function() {
    if (Auth::check()) {
        $parameters = Request::getQueryString();
        return Redirect::to('/v1/app?' . $parameters);
    }    
    return View::make('pages.user.create');
});

Route::get('/login', function () {
    if (Auth::check()) {
        $parameters = Request::getQueryString();
        return Redirect::to('/v1/app?' . $parameters);
    }
   return View::make('pages.user.login');
});

Route::get('account', function() {
    echo "account";
});

Route::get('/', ['before' => ['redirectNonAuth'], 'uses' => 'AppController@index']);
Route::get('/v1/app/{segment?}', ['before' => ['redirectNonAuth'], 'as' => 'tool', 'uses' => 'AppController@index']);

Route::get('/da', function () {
    App::setLocale('da');
    Session::set('lang', 'da');
    return Redirect::to('/');
});

Route::get('/user', 'UserController@index');

Route::get('{path}', function ($filename) {
    return Bust::css($filename);
})->where('path', '.*\.css$');
App::make('cachebuster.StripSessionCookiesFilter')->addPattern('|\.css$|');

// Login / logout endpoints
require app_path().'/routes/auth.php';

// Include routes from routes folder
require app_path().'/routes/api.php';

// Templates for modals used by Angular
require app_path().'/routes/modals.php';

// Endpoints for confirmation of user account
require app_path().'/routes/confirmation.php';

// Used to return HTML pages for Angular
require app_path().'/routes/parts.php';

require app_path().'/routes/reminders.php';

require app_path().'/routes/language.php';

require app_path().'/routes/templates.php';
require app_path().'/routes/template-blocks.php';


// External end point
require app_path().'/routes/stripe.php';

// Landing pages
require app_path().'/routes/landing-pages.php';

// Pepe - should be moved to separate site?
require app_path().'/routes/pepe.php';

// Admin panel
require app_path().'/routes/admin.php';

// Enterprise
require app_path().'/routes/enterprise.php';

// Static pages
require app_path().'/routes/static.php';


// To be removed / Potentially unused routes
require app_path().'/routes/to-be-removed.php';

// Webhooks
require app_path().'/routes/webhooks.php';


// Discount
Route::get('/discount/{code?}', 'DiscountController@check');

Route::post('/get/enterprise/confirm', 'EnterpriseController@store');


// Feedback & Annotations
require app_path().'/routes/feedback.php';


// Application Rounds
require app_path().'/routes/applications.php';


// Video Streaming
require app_path().'/routes/video.php';


// Partners
require app_path().'/routes/partners.php';

app/models/User.php
<?php
use Illuminate\Auth\Reminders\RemindableInterface;
use Illuminate\Auth\UserInterface;

use Jenssegers\Mongodb\Model as Eloquent;

use Laravel\Cashier\BillableTrait;
use Laravel\Cashier\BillableInterface;

use Pitcherific\Cashier\ExtraBillable;

use Carbon\Carbon;

use Pitcherific\UserTraits\AdminTrait;
use Pitcherific\UserTraits\ExperimentalTrait;

use Pitcherific\Traits\ActionLogTrait;

class User extends Eloquent implements UserInterface, RemindableInterface, BillableInterface
{

    use BillableTrait;
    use ExtraBillable;
    use AdminTrait;
    use ExperimentalTrait;
    use ActionLogTrait;

    protected $collection = 'users';

    protected $cardUpFront = false;

    protected $dates = ['trial_ends_at', 'subscription_ends_at'];

    protected $fillable = ['first_name', 'last_name', 'password_confirmation'];

    protected $hidden = [
        'password',
        'newsletter',
        'stripe_plan',
        'stripe_id',
        'stripe_active',
        'remember_token',
        'stripe_subscription'
    ];

    public function getEmail()
    {
        return $this->username;
    }

    public function getFullNameAttribute()
    {
        if ($this->first_name && $this->last_name) {
            return $this->first_name . ' ' . $this->last_name;
        }

        return null;
    }

    public function wantsNewsletter()
    {
        return $this->newsletter;
    }

    public function getSubscriptionEndsAt()
    {
        return $this->subscription_ends_at->format('m/d-Y');
    }

    public function getReminderEmail()
    {
        return $this->username;
    }

    public function pitches()
    {
        return $this->hasMany('Pitch');
    }

    public function videos()
    {
        return $this->hasMany('Video');
    }

    public function getPitches()
    {
        return $this->hasMany('Pitch')->orderBy('created_at', 'DESC')->get();
    }

    public function getAuthIdentifier()
    {
        return $this->getKey();
    }

    public function getAuthPassword()
    {
        return $this->password;
    }

    public function getRememberToken()
    {
        return $this->remember_token;
    }

    public function setRememberToken($value)
    {
        $this->remember_token = $value;
    }

    public function getRememberTokenName()
    {
        return 'remember_token';
    }

    public function maySave()
    {
        return $this->onTrial() && $this->subscribed();
    }

    public function isLegacyUser()
    {
        if ($this->isAttachedToEnterprise() or $this->stripeIsActive() or $this->isAdmin()) {
            return false;
        }

        $legacyDate = Carbon::create(2019, 12, 7);
        $creationDate = Carbon::parse($this->created_at);

        return ($legacyDate->gt($creationDate)) ? true : false;
    }
    /*
    |--------------------------------------------------------------------------
    | Preparing User Data as JSON
    |--------------------------------------------------------------------------
    |
    | This exposes any necessary data from the User to be used throughout
    | the tool and is especially used by Angular. If there's data that
    | you need to show on the client-side, you'll do it here.
    |
    */
    public function toJSONResponse()
    {
        $data = [
            'username'              => $this->username,
            '_id'                   => $this->_id,
            'templates'             => $this->templates ? : [],
            'subscribed'            => $this->subscribedOrWithEnterprise(),
            'ever_subscribed'       => $this->everSubscribed(),
            'confirmed'             => $this->isConfirmed(),
            'total_pitches'         => $this->getTotalPitches(),
            'enterprise_attached'   => $this->isAttachedToEnterprise(),
            'enterprise_rep'        => $this->representative ? : false,
            'enterprise_id'         => $this->enterprise_id,
            'enterprise'            => $this->fetchEnterpriseDetails(),
            'newsletter'            => $this->newsletter ? true : false,
            'first_name'            => $this->first_name ? : null,
            'last_name'             => $this->last_name ? : null,
            'full_name'             => "{$this->first_name} {$this->last_name}",
            'trial'                 => $this->onTrial() && !$this->stripeIsActive(),
            'isPayingCustomer'      => $this->stripeIsActive() || ($this->isAttachedToEnterprise() && $this->enterprise->isActive()) || false,
            'isLegacyUser'          => $this->isLegacyUser(),
            'created_at'            => $this->created_at,
            'showLegacyMessage'     => $this->seen_legacy_message ? false : true,
            'settings' => [
                'masterPitchNotice' => isset($this->masterPitchNotice) ? $this->masterPitchNotice : true
            ]
        ];

        if ($this->onTrial()) {
            $data['trial_ends_at'] = $this->getFormattedTrialEndDate();
        } elseif (isset($this->enterprise)) {
            $data['trial_ends_at'] = $this->enterprise->getExpirationDate();
        }

        if ($this->experimental) {
            $data['experimental'] = $this->experimental;
        }

        if ($this->isSubrep()) {
            $data['is_subrep'] = $this->isSubrep();
        }

        if ($this->isAdmin()) {
            $data['admin'] = $this->admin;
        }

        /**
         * ASH: This will make it possible to lock certain templates
         * and features if the user has once been subscribed or
         * once had a PRO trial. Is this the right way?
         * The expired check only checks whether the user is not subscribed anymore
         *
         * Trial Situation:
         *
         * Former Enterprise situation:
         *
         * Former PRO situation:
         */
        if (!$this->isSubrep() &&
            !$this->subscribedOrWithEnterprise() &&
            ($this->isFormerPro() || $this->isFormerTrialUser())
        ) {
            $data['expired'] = true;
        }

        if ($this->enterprise_id) {
            if (isset($this->needs_feedback)) {
                $data['needs_feedback'] = $this->needs_feedback;
            }
        }

        return $data;
    }

    public function isFormerPRO()
    {
        if ($this->everSubscribed() && $this->expired()) {
            return true;
        }

        return false;
    }

    public function isFormerTrialUser()
    {
        if (!is_null($this->trial_ends_at) && $this->expired()) {
            return true;
        }

        return false;
    }

    public function getFormattedTrialEndDate()
    {
        $format = 'd. M, Y'; // Danish Fallback

        if (Session::get('lang') != 'da') {
            $format = 'Y-m-d';
        }

        $date = $this->trial_ends_at;
        $formatted_end_date = date($format, strtotime($date));
        return $formatted_end_date;
    }

    public function fetchEnterpriseDetails()
    {
        $enterprise = $this->getEnterprise();

        if ($enterprise) {
            return [
              'name' => $enterprise->name,
              'context' => $enterprise->context,
              'branded' => $enterprise->branded,
              'logo_url' => $enterprise->logo_url,
              'plan' => $enterprise->stripe_plan ? $enterprise->stripe_plan === 'dashboard_agency_yrly' ? 'Agency' : 'Team' : 'Enterprise',
              'feature_flags' => $enterprise->feature_flags,
              'features_disabled' => $enterprise->features_disabled
            ];
        }

        return [];
    }

    public function isAttachedToEnterprise()
    {
        return $this->checkForEnterprise();
    }

    public function getTotalPitches()
    {
        return $this->getPitches()->count();
    }

    public function pitchesCountRelation()
    {
        $query = $this->hasOne('Pitch')->selectRaw('user_id, count(*) as count')->groupBy('user_id');
        return $query;
    }

    public function isConfirmed()
    {
        if ($this->isAttachedToEnterprise()) {
            return true;
        }

        return ( $this->confirmed ) ? true : false;
    }

    public function setConfirmed($status)
    {
        $this->confirmed = $status;
    }

    public function isEnterpriseRep()
    {
        return isset($this->represents_enterprise);
    }

    public function getEnterpriseId()
    {
        if (isset($this->represents_enterprise)) {
            return $this->represents_enterprise;
        } elseif (isset($this->enterprise_id)) {
            return $this->enterprise_id;
        } else {
            return null;
        }
    }

    public function getEnterprise()
    {
        return Enterprise::where('_id', '=', $this->getEnterpriseId())->first();
    }

    public function getConfirmationCode()
    {
        return $this->confirmation_code;
    }

    public function hasConfirmationCode()
    {
        return isset($this->confirmation_code);
    }

    public function generateConfirmationCode()
    {
        $this->confirmation_code = str_random(20);
    }


    public function enterprise()
    {
        return $this->belongsTo('Enterprise');
    }

    /**
     * Handles checking if the current user is associated
     * with an Enterprise customer in some way.
     *
     * If so, and they don't have access to PRO features,
     * we will upgrade them for as long as the Enterprise
     * customer exists and for as long as they themselves
     * are associated with the Enterprise itself.
     *
     * @return JSON Response
     */
    public function checkForEnterprise()
    {
        $enterprise = Enterprise::where('_id', '=', $this->enterprise_id)->first();
        if ($enterprise === null) {
            return false;
        }

        return true;
    }

    /**
     * Does a very simple check to see whether the user is
     * associated with an Enterprise or not.
     * @param  [type]  $id [description]
     * @return boolean     [description]
     */

app/views/modals/buy-template.blade.php
{{ HTML::modalOpen(Lang::get('pitcherific.buy_template_modal.title'), 'event-response-modal', 'modal--slim') }}
  {{ HTML::modalBodyOpen() }}
     <div class="response-message">
      <div class="h2 has--no-top-margin margined--slightly-in-the-bottom">
        <strong>@{{ template.title }}</strong>
      </div>
      <p ng-bind-html="template_description"></p>
     </div>

     <div class="modal-media" style="background-color: @{{ template.details.theme }}">
       
       <div class="modal-media__content">
         <div class="h2"><strong>{{ Lang::get('pitcherific.buy_template_modal.details.title') }}</strong></div>
         
         <ul class="modal-media__list">
           <li>@{{ template.details.bullets.one }}</li>
           <li>@{{ template.details.bullets.two }}</li>
           <li>@{{ template.details.bullets.three }}</li>
         </ul>
       </div>

       <i class="fa fa-file-text-o"></i>
     </div>

     <button class="button button--bold button--golden margined--slightly-in-the-bottom" ng-click="buyTemplate(template)"><i class="fa fa-shopping-cart"></i> {{ Lang::get('pitcherific.buy_template_modal_custom.unlock_button_text') }}
     </button>
     <div>
        
        <hr>
        
        <small>
          {{ Lang::get('pitcherific.buy_template_modal.small_print') }}
        </small>

     </div>
  {{ HTML::modalBodyClose() }}
{{ HTML::modalClose() }}

app/views/modals/feedback.blade.php
{{ HTML::modalOpen(Lang::get('ui.settings.share.submenu.feedback'), 'feedback-modal', 'modal--slim') }}
  {{ HTML::modalBodyOpen() }}
     @include('components.feedback_url', ['size' => 'md'])
     <div class="margined--slightly-in-the-top" ng-if="feedbackCtrl.isPublic()"><small><strong>Heads up: </strong>{{ Lang::get('ui.modals.feedback.description') }} "@{{ feedbackCtrl.pitch().title }}".</small></div>
  {{ HTML::modalBodyClose() }}
{{ HTML::modalClose() }}

app/views/modals/login.blade.php
{{ HTML::modalOpen(null, 'login-modal', 'modal--slim') }}

  @if(Session::has('discount'))
    @include('components.messages.discount')
  @endif

  <div
   class="alert alert-danger has--no-rounded-corners has--no-bottom-margin"
   ng-class="{ 'alert-fades-out' : error }"
   ng-if="error">
   @{{ error }}
  </div>

    <form name="loginForm" ng-submit="login(creds)" class="login-form is--unselectable">
      {{ HTML::modalBodyOpen() }}

        <div class="form-group">
          <label class="is--block">{{ Lang::get('pitcherific.labels.email') }}
            <input
             type="email"
             name="username"
             class="form-control has--help-block"
             autocomplete="off"
             ng-model="creds.username"
             title="{{ Lang::get('pitcherific.labels.login_email_help_text') }}"
             ng-model-options="{debounce: { 'default' : 500, 'blur' : 0}}"
             required
             mailcheck
             autofocus>
          </label>
        </div>

        <div
         class="form-group has--checkbox"
         ng-class="{ 'margined--slightly-in-the-bottom' : !showCreateForm }">

          <label class="is--block">{{ Lang::get('pitcherific.labels.password') }}
            <span class="pull-right" ng-if="!creating && !showCreateForm">
               <a class="text text--as-link no-underline" ng-click="openRemindPasswordModal()">{{Lang::get('pitcherific.copy.forgot_password')}}</a>
            </span>
            <span class="text-muted pull-right" ng-if="creating || showCreateForm">
             {{ Lang::get('pitcherific.labels.login_password_help_text') }}
            </span>
          </label>
            <div class="input-group">
              <input
               type="@{{ showPassword ? 'text' : 'password' }}"
               name="password"
               class="form-control is--unmaskable"
               ng-model="creds.password"
               pattern=".{6,}"
               title="{{ Lang::get('pitcherific.labels.login_password_help_text') }}"
               autocomplete="off"
               required
              />
              <div class="input-group-addon">
                <label class="checkbox-container">
                  <input
                    type="checkbox"
                    class="input--inline"
                    ng-model="showPassword"
                    ng-checked="false"
                    tabindex="-1"/>
                  <span class="align-middle align-baseline-middle-sm">
                    {{ Lang::get('pitcherific.labels.show_password') }}
                  </span>
                </label>
              </div>
            </div>
        </div>

        <div class="form-group has--checkbox" ng-if="creating || showCreateForm">
          <label class="is--block">{{ Lang::get('pitcherific.labels.confirm_password') }}
            <input
              type="@{{ showPassword ? 'text' : 'password' }}"
               name="password_confirmation"
               class="form-control is--unmaskable"
               ng-model="creds.password_confirmation"
               pattern=".{6,}"
               title="{{ Lang::get('pitcherific.labels.login_password_confirmation_help_text') }}"
               compare-to="creds.password"
               autocomplete="off"
               required
              />
          </label>
        </div>

        <div class="form-group" ng-if="creating || showCreateForm">
          <label class="checkbox-container">
            <input
             type="checkbox"
             class="input--inline"
             ng-model="creds.terms"
             required>
             <span class="align-middle align-baseline-middle-sm">{{ Lang::get('pitcherific.copy.signup_terms') }}</span>
          </label>
        </div>

      {{ HTML::modalBodyClose() }}

      {{ HTML::modalFooterOpen() }}
          <div class="text-left">
            <button
             type="submit"
             class="button button--bold button--success button--inline button--lg"
             ng-class="{'button--golden' : !loginButton.success }"
             ng-disabled="!loginForm.$valid || isSubmitting">
             <span ng-if="isSubmitting"><i class="fa fa-spinner fa-spin"></i> </span>
             <span ng-if="showCreateForm">{{ Lang::get('pitcherific.copy.create_new_account') }}</span>
             <span ng-if="!showCreateForm">@{{ loginButton.message }}</span>
            </button>
          </div>
      {{ HTML::modalFooterClose() }}
    </form>
{{ HTML::modalClose() }}

app/views/modals/pitch-review.blade.php
{{ HTML::modalOpen(Lang::get('pitcherific.review_modal.title'), 'pitch-review-modal') }}
  {{ HTML::modalBodyOpen() }}

        {{ Lang::get('pitcherific.review_modal.choose_pitch_intro') }}

        <div class="row">
          <div class="col-sm-6">

            <select
             selectpicker
             name="pitchReviewPitchSelector"
             id="pitchReviewPitchSelector"
             ng-model="review.pitchId"
             class="bootstrap-select--fluid bootstrap-select--margin-bottom"
             data-none-selected-text="{{ Lang::get('pitcherific.labels.nothing_selected') }}"
             ng-options="pitch._id as pitch.title for pitch in pitches">
            </select>

          </div>

          <div class="col-sm-6">


        @if (Session::get('lang') == 'da')
          <p><small>Prisen afhænger af længden på dit pitch.<br> Et <strong>Simple Review</strong> for et 4 minutters pitch koster f.eks. $46 (ca. DKK 305).</p>
        @else
          <p><small>The price depends on the length of your pitch.<br> A <strong>Simple Review</strong> of a 4 minute pitch costs $46.<br></p>
        @endif


          </div>
        </div>

        {{ Lang::get('pitcherific.review_modal.intro') }}

        <br>

          <ul class="list list--choice-blocks clearfix">
            <li class="list__item choice-block is--unselectable" title="{{ Lang::get('pitcherific.review_modal.click_to_choose') }}">
              <input type="radio" name="pitch-review-choice" id="simpleReview" value="simple" ng-model="review.type" >
              <label for="simpleReview">

                <div class="choice-block__title">{{ Lang::get('pitcherific.review_modal.simple') }}</div>
                <div class="choice-block__description">
                 {{ Lang::get('pitcherific.review_modal.simple_description') }}
                </div>
                <span class="choice-block__meta text--right">
                  @if( $user->subscribed() )
                    <span class="meta__discounted-price">@{{ simplePrice }}</span>
                  @else
                    <span ng-if="simplePrice === undefined">{{ Lang::get('pitcherific.prices.reviews.simple') }}</span>
                    @{{ simplePrice }}
                  @endif
                </span>
              </label>
            </li>

            <li class="list__item choice-block is--unselectable" title="{{ Lang::get('pitcherific.review_modal.click_to_choose') }}">
              <input type="radio" name="pitch-review-choice" id="completeReview" value="complete" ng-model="review.type">
              <label for="completeReview">

                <div class="choice-block__title">{{ Lang::get('pitcherific.review_modal.complete') }}</div>
                <div class="choice-block__description">
                  {{ Lang::get('pitcherific.review_modal.complete_description') }}
                </div>
                <span class="choice-block__meta text--right">
                  @if( $user->subscribed() )
                    <span class="meta__discounted-price">@{{ completePrice }}</span>
                  @else
                    <span ng-if="completePrice === undefined">{{ Lang::get('pitcherific.prices.reviews.complete') }}</span>
                    @{{ completePrice }}
                  @endif
                </span>
              </label>

            </li>
          </ul>
        </p>
      {{ HTML::modalBodyClose() }}

      {{ HTML::modalFooterOpen() }}
        <button type="button" class="button button--lg btn-block button--block button--bold button--success" ng-click="checkout()" ng-disabled="review.type === undefiend || review.pitchId === undefined">
          {{ Lang::get('pitcherific.review_modal.checkout_button_text') }}
        </button>
      {{ HTML::modalFooterClose() }}

{{ HTML::modalClose() }}

app/views/modals/post-checkout.blade.php
{{ HTML::modalOpen(Lang::get('pitcherific.copy.post_checkout_modal_headline'), 'post-checkout-modal', 'modal--slim') }}
    {{ HTML::modalBodyOpen() }}
      {{ Lang::get('pitcherific.copy.post_checkout_modal_content') }}

      <div class="my2 text--center">
        <button
        class="button button--bold button--success button--inline button--lg"
        ng-bind="'Lets get to work'"
        ng-click="vm.ok()">
        </button>
      </div>

    {{ HTML::modalBodyClose() }}
{{ HTML::modalClose() }}

app/views/modals/pro-signup.blade.php
{{ HTML::modalOpen(Lang::get('pitcherific.copy.secure_sign_up'), 'premium-signup-modal', 'modal--slim') }}

    @if(Session::has('discount'))
      @include('components.messages.discount', [
        'alert_class' => 'alert alert-success alert-borderless has--no-bottom-margin text-center'
      ])
    @endif

    {{ HTML::modalBodyOpen() }}

    <div class="row">
      <div class="col-sm-6">
        <div class="p-branding mb4 flex flex-column items-center text--center">
          <div ng-bind="vm.selectedPlan"></div>
          <img
            class="c-logo-mark"
            src="{{ Bust::url('assets/img/icons-touch/apple-touch-icon-76x76.png') }}" />
          <h3 class="h3" ng-bind="activePlan().label + ' ' + '{{ Lang::get('pitcherific.modals.pro_signup.membership_label') }}'"></h3>
          <h2 class="h2 mt0 mb2" ng-bind="'$' + activePlan().value + '/' + activePlan().unit"></h2>
        </div>
        <div class="text--center my2">
            <img
            class="c-side-image mx-auto"
            src="{{ Bust::url('assets/img/checkout_side_image.jpg') }}" />
          <h2 class="h2">{{ Lang::get('pitcherific.modals.pro_signup.aside_promo_text') }}</h2>    
        </div>
      </div>
      <div class="col-sm-6">
        @include('includes.credit-card-form', [
            'submit' => 'vm.doSignupNew(vm.signup)',
            'model' => 'signup',
            'has_choice_selector' => true,
        ])
      </div>
    </div>

    {{ HTML::modalBodyClose() }}
    @include('includes.secure-message')
{{ HTML::modalClose() }}

app/views/modals/remind-password.blade.php
{{ HTML::modalOpen(Lang::get('pitcherific.copy.forgot_password'), 'remind-password-modal', 'modal--slim') }}

  <form name="remindForm" ng-submit="submit(creds)">
    {{ HTML::modalBodyOpen() }}
      
      <div class="form-group">
        <label class="is--block">
          {{ Lang::get('pitcherific.labels.email') }}
          <input 
           type="email" 
           class="form-control input-lg" 
           name="username" 
           placeholder="{{Lang::get('pitcherific.copy.forgot_password_email_placeholder')}}" autocomplete="off" ng-model="creds.username" required>
        </label>
      </div>

      <div class="remind-alert alert" ng-class="{'alert-success' : responseMessage.success, 'alert-danger': !responseMessage.success}" role="alert" ng-if="responseMessage">
        <p class="remind-alert-text">@{{ responseMessage.message }}</p>
      </div>
    {{ HTML::modalBodyClose() }}

    {{ HTML::modalFooterOpen() }}
       <input type="submit" class="button btn-lg button--bold button--success" value="{{Lang::get('pitcherific.copy.forgot_password_button')}}">
    {{ HTML::modalFooterClose() }}
  </form>

{{ HTML::modalClose() }}

app/views/modals/screen-recording-complete.blade.php
{{ HTML::modalOpen('Video pitch recorded! Let\'s wrap it up', 'video-share-modal', 'modal--slim') }}
  {{ HTML::modalBodyOpen() }}

  <section>
      <div>
        <div class="flex flex-column mr2">
          <label>Video title</label>
          <input
            type="text"
            class="form-control"
            ng-model="vm.video.name"
            ng-blur="vm.updateName(vm.video, vm.video.name)">
        </div>
        
        <div class="flex flex-column mr2">
          <label class="mb0">Add to project folder</label>
          <div class="dropdown pitch__submenu">
            <button
              id="ProjectFolderSelect"
              class="btn btn-default dropdown-toggle"
              type="button"
              data-toggle="dropdown"
              ng-cloak>
              <span class="pitch__submenu-caret">Project folders <i class="fa fa-caret-down"></i></span>
            </button>

            <ul
              class="dropdown-menu dropdown-menu-right">
              <li
                ng-repeat="workspace in WorkspaceService.workspaces() track by workspace._id">
                <div class="flex forced items-center justify-between">
                  <span ng-bind="workspace.title"></span>
                  <input
                    name="WorkspaceId"
                    ng-attr-data-workspace="@{{ workspace._id }}"
                    type="checkbox"
                    class="width-auto"
                    ng-click="vm.updateVideoWorkspaces({ video_id: vm.video._id, workspace_ids: vm.getWorkspaceIds() })">
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <div class="flex items-center">
        <div class="mr3">
            <div
              title="Retake video" 
              class="flex items-center"
              ng-click="vm.startRecording()">
              <i class="fa fa-repeat is-clickable mr1"></i>
              <span>Re-take</span>
            </div>
          </div>      
        <div class="mr1">
          <i
            title="Delete video" 
            class="fa fa-trash is-clickable"
            ng-click="vm.deleteVideo(vm.video)"></i>
        </div>
      </div>
    </section>

  {{ HTML::modalBodyClose() }}

  {{ HTML::modalFooterOpen() }}
    <div class="text-left">
      <button
       class="button button--bold button--success button--inline button--lg"
       ng-click="vm.finish()">
        <span>{{ Lang::get('ui.components.video_recorder.modals.store.confirm_save_buttton_text') }}</span>
      </button>
    </div>
  {{ HTML::modalFooterClose() }}
{{ HTML::modalClose() }}

app/views/modals/segments-angular.blade.php
{{ HTML::modalOpen(trans('ui.modals.segments.title'), '', '') }}
  {{ HTML::modalBodyOpen() }}
    @include('pages.home.components.who.components.personas', [
        'personaContainerClasses' => 'c-persona-block col-12 col-sm-6 col-md-6',
        'personas' => [
          'business' => [
            'name' => trans('ui.pages.home.sections.who.blocks.business.title'),
            'description' => trans('ui.pages.home.sections.who.blocks.business.description'),
            'path' => '/v1/app/business',
            'bgImage' => 'assets/img/who/business.jpg',
            'class' => 'persona--business'
          ],
          'education' => [
              'name' => trans('ui.pages.home.sections.who.blocks.education.title'),
              'description' => trans('ui.pages.home.sections.who.blocks.education.description'),
              'path' => '/v1/app/education',
              'bgImage' => 'assets/img/who/education.jpg',
              'class' => 'persona--education'
          ],
          'incubators' => [
              'name' => trans('ui.pages.home.sections.who.blocks.incubators.title'),
              'description' => trans('ui.pages.home.sections.who.blocks.incubators.description'),
              'path' => '/v1/app/incubator',
              'bgImage' => 'assets/img/who/incubator.jpg',
              'class' => 'persona--incubator'
          ],
          'employment' => [
              'name' => trans('ui.pages.home.sections.who.blocks.job.title'),
              'description' => trans('ui.pages.home.sections.who.blocks.job.description'),
              'path' => '/v1/app/job',
              'bgImage' => 'assets/img/who/career.jpg',
              'class' => 'persona--job'
          ]          
        ]
      ])
    {{ HTML::modalBodyClose() }}
{{ HTML::modalClose() }}
  

app/views/modals/video-guides.blade.php
{{ HTML::modalOpen('Video Guides', 'video-guide-modal', 'modal--video') }}
  {{ HTML::modalBodyOpen() }}
    
    <div class="alert alert-warning mb0 text-right" >
      <i class="fa fa-arrow-down top-5 ml1 mr1 pull-right"></i>
      <strong class="pull-right">{{ trans('ui.modals.video_guides.playlist_notification') }}</strong>
    </div>

    <iframe
     width="100%"
     height="560"
     src="https://www.youtube.com/embed?listType=playlist&list=PLn9BGJthPHQeehNjdn2FotYshiUclQ2Uk&vq=hd720&modestbranding=1&rel=0&showinfo=1"
     frameborder="0"
     allowfullscreen></iframe>

  {{ HTML::modalBodyClose() }}
{{ HTML::modalClose() }}